os: windows
apps:
  meet:
    mic: ["ctrl", "d"]
    cam: ["ctrl", "e"]
    window_hints:
      - ".meet.google.com"
      - "Meet -"
      - "Google Meet"
      - "Meet â€”"
      - "Meet:"
      - "Microsoft Edge"
      - "Google Chrome"
      - "Chrome"
